### ISSUE TITLE
Cannot save multi-level freq. distribution

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#1312]

**Comment by tomachalek** [comment]
```
 [controller] ERROR: max() arg is an empty sequence
Traceback (most recent call last):
  File "/opt/kontext/production/public/../lib/controller.py", line 783, in run
    methodname, tmpl, result = self.process_method(path[0], path, named_args)
  File "/opt/kontext/production/public/../lib/controller.py", line 893, in process_method
    return self.process_error(ex, methodname, pos_args, named_args)
  File "/opt/kontext/production/public/../lib/controller.py", line 858, in process_error
    return self.process_method(em, pos_args, named_args)
  File "/opt/kontext/production/public/../lib/controller.py", line 893, in process_method
    return self.process_error(ex, methodname, pos_args, named_args)
  File "/opt/kontext/production/public/../lib/controller.py", line 851, in process_error
    raise e2
ValueError: max() arg is an empty sequence
```
