### ISSUE TITLE
Error in worker.calculate_freqs

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#1320]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/kontext/production/worker.py", line 264, in calculate_freqs
    ans = freq_calc.calc_freqs_bg(args)
  File "/opt/kontext/production/lib/freq_calc.py", line 251, in calc_freqs_bg
    for cr in args.fcrit]
  File "/opt/kontext/production/lib/pyconc.py", line 252, in xfreq_dist
    norms = [norms2_dict[x] for x in words]
KeyError: u''
```

**Comment by tomachalek** [comment]
Fixed
