### ISSUE TITLE
It is possible to enforce an almost permanent error message on first_form

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#2227]
... by manual url arg setting
```
Traceback (most recent call last):
  File "/opt/kontext/production/public/../lib/controller/__init__.py", line 739, in run
    methodname, tmpl, result = self.process_action(path[0], path, named_args)
  File "/opt/kontext/production/public/../lib/controller/__init__.py", line 859, in process_action
    return self.handle_action_error(ex, methodname, pos_args, named_args)
  File "/opt/kontext/production/public/../lib/controller/__init__.py", line 806, in handle_action_error
    raise e2
AttributeError: 'Args' object has no attribute ''
```

**Comment by tomachalek** [comment]
Unable to reproduce :rage:
