### ISSUE TITLE
Cannot sign-in

### ISSUE THREAD

**Issue by PeterGilles** [czcorpus/kontext#2310]
KonText is running on my server better and better. My main problem at the moment is: When not logged in, I am getting the pop-up to sign-in, but I cannot click on 'Sign-in' (not clickable). There are no error neither in the Javascript console nor in the application log.

**Comment by PeterGilles** [comment]
Could this problem be related to the redis server? I see that I have a 'redis-server' and 'redis_6379' as a service.

**Comment by PeterGilles** [comment]
In the meantime I reconfigured redis and in fact I now can login to konText. Is it necessary to run `install.py users.json` everytime, konText is recompiled?
But now I am having the problem that I cannot search the corpus at all. The browser is waiting for data, but there is no error and no process running. The last messages in the application log are:

```2018-04-19 11:04:02,210 [werkzeug] INFO: 192.168.4.180 - - [19/Apr/2018 11:04:02] "POST /user/login?return_url=http%3A%2F%2Fengelmann.uni.lu%3A5000%2Ffirst_form%3Fcorpname%3Dkorpus HTTP/1.1" 303 -
2018-04-19 11:04:02,694 [QUERY] INFO: {"user_id": 1, "proc_time": 0.0101, "settings": {"ctxattrs": "word", "attr_vmode": "visible", "pagesize": 40, "wlpagesize": 25, "cql_editor": 1, "kwicrightctx": "10", "attrs": "word", "cup_hl": "q", "citemsperpage": 50, "kwicleftctx": "-10"}, "pid": 32722, "request": {"HTTP_USER_AGENT": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:59.0) Gecko/20100101 Firefox/59.0", "REMOTE_ADDR": "192.168.4.180"}, "action": "first_form", "params": {"corpname": "korpus"}, "user": "peter", "date": "2018-04-19 11:04:02.693875"}
2018-04-19 11:04:02,699 [werkzeug] INFO: 192.168.4.180 - - [19/Apr/2018 11:04:02] "GET /first_form?corpname=korpus HTTP/1.1" 200 -
2018-04-19 11:04:03,183 [werkzeug] INFO: 192.168.4.180 - - [19/Apr/2018 11:04:03] "GET /files/img/starred.svg HTTP/1.1" 200 - 
```


My `config.xml`:


```<kontext>
<theme>
<name>default</name>
<css/>
<!-- <logo>schnessen.png</logo>-->
<logo>kontext-logo.svg</logo>
<logo_mouseover>kontext-logo_s.svg</logo_mouseover>
<logo_href>http://engelmann.uni.lu:5000</logo_href>
 
<!-- change this according to your settings -->
<logo_inline_css>width: 200px</logo_inline_css>
<fonts/>
</theme>
<global>
<deployment_id>20181031_v6</deployment_id>
 
<!-- can flush browser's cache when updating app even if HTTP caching headers are not ok -->
<manatee_path />
<umask>002</umask>
<debug>false</debug>
<maintenance>false</maintenance>
<profile_log_path/><!-- leave this empty unless you want to do a low-level debugging -->
<max_attr_list_size>30</max_attr_list_size>
<translations>
<language label="česky">cs_CZ</language>
<language label="English">en_US</language>
</translations>
        <upload_cache_dir>/tmp/kontext-upload</upload_cache_dir>
        <user_filter_files_dir>/var/lib/corpora/user_filter_files</user_filter_files_dir>
        <periodic_tasks conf="/home/administrator/kontext/conf/beatconfig.py">celery</periodic_tasks>
        <conc_line_max_group_num>99</conc_line_max_group_num>
        <calc_backend conf="/home/administrator/kontext/conf/celeryconfig.py">celery</calc_backend>
<action_path_prefix/>
<static_files_prefix>/files</static_files_prefix>
<use_conc_toolbar>0</use_conc_toolbar>
</global>
<mailing/>
<logging>
<path>/var/log/kontext/application.log</path>
<file_size>5000000</file_size>
<num_files>10</num_files>
<values>
<item>environ:REMOTE_ADDR</item>
<item>environ:HTTP_USER_AGENT</item>
<item>date</item>
<item>user</item>
<item>user_id</item>
<item>action</item>
<item>params</item>
<item>settings</item>
<item>proc_time</item>
<item>pid</item>
</values>
</logging>
<corpora>
        <manatee_registry>/var/lib/corpora/registry</manatee_registry>
        <manatee_registry_locale>de_DE</manatee_registry_locale>
        <users_subcpath>/var/lib/corpora/subcorp</users_subcpath>
        <freqs_precalc_dir>/var/lib/corpora/freqs-precalc</freqs_precalc_dir> <!-- this is optional -->
        <freqs_cache_dir>/var/lib/corpora/freqs-cache</freqs_cache_dir>
        <freqs_cache_ttl>3600</freqs_cache_ttl>
        <freqs_cache_min_lines>100</freqs_cache_min_lines>
        <colls_cache_dir>/var/lib/corpora/colls-cache</colls_cache_dir>
        <colls_cache_ttl>3600</colls_cache_ttl>
        <colls_cache_min_lines>50</colls_cache_min_lines>
        <conc_dir>/var/lib/corpora/conc</conc_dir>
        <default_corpora>
            <item>korpus</item>
            <!-- item>insert_your_default_corpus_here</item -->
</default_corpora>
<speech_files_path/>
<empty_attr_value_placeholder>--</empty_attr_value_placeholder>
<multilevel_freq_dist_max_levels>10</multilevel_freq_dist_max_levels>
<right_interval_char>+</right_interval_char>
<left_interval_char/>
<interval_char>±</interval_char>
</corpora>
<plugins>
<application_bar/>
<auth>
<module>default_auth</module>
 <js_module>defaultAuth</js_module>
<auth_cookie_name>kontext_session</auth_cookie_name>
<anonymous_user_id>0</anonymous_user_id>
            <login_url>http://engelmann.uni.lu:5000/user/login?continue=%s</login_url>
            <logout_url>http://engelmann.uni.lu:5000/user/logoutx</logout_url>
</auth>
<conc_cache>
<module>redis_conc_cache</module>
<cache_dir extension-by="default">/var/lib/corpora/cache</cache_dir>
</conc_cache>
<conc_persistence>
<module>default_conc_persistence</module>
<ttl_days extension-by="default">100</ttl_days>
<anonymous_user_ttl_days extension-by="default">7</anonymous_user_ttl_days>
</conc_persistence>
        <corparch>
            <module>default_corparch</module>
            <js_module>defaultCorparch</js_module>
            <file>/home/administrator/kontext/conf/corplist.xml</file>
            <root_elm_path>/corplist</root_elm_path>
            <tag_prefix extension-by="default">+</tag_prefix>
            <max_num_hints extension-by="default">10</max_num_hints>
            <max_num_favorites extension-by="default">15</max_num_favorites>
            <default_page_list_size extension-by="default">30</default_page_list_size>
        </corparch>
<db>
<module>redis_db</module>
<host extension-by="default">localhost</host>
<port extension-by="default">6379</port>
<id extension-by="default">1</id>
</db>
<export>
<csv>default_csv</csv>
<xlsx>default_xlsx</xlsx>
</export>
<export_freq2d>
<xlsx>default_xlsx</xlsx>
</export_freq2d>
<footer_bar/>
<getlang>
<module>default_getlang</module>
<cookie extension-by="default">kontext_toolbar_lang</cookie>
<fallback_lang extension-by="default">en_US</fallback_lang>
</getlang>
<live_attributes/>
<menu_items>
<module>default_menu_items</module>
            <data_path extension-by="default">/home/administrator/kontext/conf/main-menu.sample.json</data_path>
</menu_items>
<query_storage>
<module>default_query_storage</module>
<js_module>defaultQueryStorage</js_module>
<page_num_records>10</page_num_records>
<num_kept_records extension-by="default">10</num_kept_records>
</query_storage>
<settings_storage>
<module>default_settings_storage</module>
<excluded_users>
<item>1</item>
<item>3</item>
</excluded_users>
</settings_storage>
<sessions>
<module>default_sessions</module>
<ttl>14400</ttl>
</sessions>
<subcmixer/>
<subc_restore/>
<syntax_viewer/>
<taghelper>
<module>default_taghelper</module>
<clear_interval extension-by="default">86400</clear_interval>
<tags_cache_dir extension-by="default">/path/to/tags/cache</tags_cache_dir>
<taglist_path extension-by="default">/path/to/tag/xml/def</taglist_path>
<tags_src_dir extension-by="default">/path/to/tag/src/data</tags_src_dir>
</taghelper>
<user_items>
<module>default_user_items</module>
</user_items>
<chart_export>
<module>default_chart_export</module>
</chart_export>
        <issue_reporting />
<!-- <issue_reporting>
<module>default_issue_reporting</module>
</issue_reporting>
-->
<token_connect />
<!-- <token_connect>
<module>default_token_connect</module>
<providers_conf extension-by="default">path/to/providers/conf.json</providers_conf>
<cache_db_path extension-by="default">path/to/cache/sqlite3/db/file</cache_db_path>
<cache_ttl_days extension-by="default">7</cache_ttl_days>
<cache_rows_limit extension-by="default">100000</cache_rows_limit>
</token_connect> -->
<kwic_connect />
<!--<kwic_connect>
<module>default_kwic_connect</module>
<js_module>defaultKwicConnect</js_module>
<providers_conf extension-by="default">path/to/providers/conf.json</providers_conf>
</kwic_connect> -->
</plugins>
</kontext>
```
Any help is appreciated.

**Comment by PeterGilles** [comment]
It appears that can display the wordlist of a corpus correctly, but when I try to display a search, either from the wordlist or by a simple query, the system is stuck/not reacting.

**Comment by tomachalek** [comment]
I've tried the config above (with some minor modifications in filesystem paths) and it works on my development machine. But from your description, it seems that it may be related to the Celery worker. Based on your config (the environment variables one, not conf/celeryconfig.py) it should log its activity to a file. But the fact that KonText got stuck may indicate that KonText is unable to reach the Celery server at all (= no log record in such case). Please make sure that Celery receives commands from KonText and feel free to post Celery log here for further investigation.

**Comment by PeterGilles** [comment]
Celery could be the culprit. I followed the installation advise and did the configuration again. It changed nothing. I have not experience at all with Celery, I cannot find processes related it to and also no logfile.

**Comment by PeterGilles** [comment]
Thank you, Tomas. In the meantime I at least found an error log. A module named 'abstract' is not found.

```May 03 14:23:36 Engelmann2 systemd[1]: Starting Celery Service...
-- Subject: Unit celeryd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit celeryd.service has begun starting up.
May 03 14:23:37 Engelmann2 sh[7846]: Traceback (most recent call last):
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
May 03 14:23:37 Engelmann2 sh[7846]:     "__main__", mod_spec)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
May 03 14:23:37 Engelmann2 sh[7846]:     exec(code, run_globals)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/__main__.py", line 18,
May 03 14:23:37 Engelmann2 sh[7846]:     main()
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/__main__.py", line 14,
May 03 14:23:37 Engelmann2 sh[7846]:     _main()
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/bin/celery.py", line 3
May 03 14:23:37 Engelmann2 sh[7846]:     cmd.execute_from_commandline(argv)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/bin/celery.py", line 4
May 03 14:23:37 Engelmann2 sh[7846]:     super(CeleryCommand, self).execute_from_commandline(argv)))
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/bin/base.py", line 279
May 03 14:23:37 Engelmann2 sh[7846]:     argv = self.setup_app_from_commandline(argv)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/bin/base.py", line 481
May 03 14:23:37 Engelmann2 sh[7846]:     self.app = self.find_app(app)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/bin/base.py", line 503
May 03 14:23:37 Engelmann2 sh[7846]:     return find_app(app, symbol_by_name=self.symbol_by_name)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/app/utils.py", line 35
May 03 14:23:37 Engelmann2 sh[7846]:     sym = symbol_by_name(app, imp=imp)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/bin/base.py", line 506
May 03 14:23:37 Engelmann2 sh[7846]:     return imports.symbol_by_name(name, imp=imp)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/kombu/utils/imports.py", line
May 03 14:23:37 Engelmann2 sh[7846]:     module = imp(module_name, package=package, **kwargs)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/local/lib/python3.5/dist-packages/celery/utils/imports.py", lin
May 03 14:23:37 Engelmann2 sh[7846]:     return imp(module, package=package)
May 03 14:23:37 Engelmann2 sh[7846]:   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_modul
May 03 14:23:37 Engelmann2 sh[7846]:     return _bootstrap._gcd_import(name[level:], package, level)
May 03 14:23:37 Engelmann2 sh[7846]:   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
May 03 14:23:37 Engelmann2 sh[7846]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
May 03 14:23:37 Engelmann2 sh[7846]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
May 03 14:23:37 Engelmann2 sh[7846]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
May 03 14:23:37 Engelmann2 sh[7846]:   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
May 03 14:23:37 Engelmann2 sh[7846]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_remov
May 03 14:23:37 Engelmann2 sh[7846]:   File "/home/administrator/kontext/worker.py", line 44, in <module>
May 03 14:23:37 Engelmann2 sh[7846]:     import initializer
May 03 14:23:37 Engelmann2 sh[7846]:   File "/home/administrator/kontext/lib/initializer.py", line 21, in <module
May 03 14:23:37 Engelmann2 sh[7846]:     import plugins
May 03 14:23:37 Engelmann2 sh[7846]:   File "/home/administrator/kontext/lib/plugins/__init__.py", line 20, in <m
May 03 14:23:37 Engelmann2 sh[7846]:     from abstract import PluginException
May 03 14:23:37 Engelmann2 sh[7846]: ImportError: No module named 'abstract'
May 03 14:23:37 Engelmann2 sh[7846]: celery multi v4.1.0 (latentcall)
May 03 14:23:37 Engelmann2 sh[7846]: > Starting nodes...
May 03 14:23:37 Engelmann2 sh[7846]:         > worker1@Engelmann2: * Child terminated with exit code 1
May 03 14:23:37 Engelmann2 sh[7846]: FAILED
May 03 14:23:38 Engelmann2 systemd[1]: celeryd.service: Control process exited, code=exited status=1
May 03 14:23:38 Engelmann2 systemd[1]: Failed to start Celery Service.
-- Subject: Unit celeryd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit celeryd.service has failed.
-- 
-- The result is failed.```

**Comment by tomachalek** [comment]
From the log, I can see that your Celery runs within _Python 3.5_ which is a problem because KonText runs only in _Python 2.6/2.7_ Please make sure you install KonText dependencies (including Celery) for Python 2.

**Comment by PeterGilles** [comment]
Thank you. One step further. Celery now runs for Python 2. I am now getting other errors:

```RuntimeError: FileAccessError (/var/lib/corpora/cache/korpus/e4bdadeb379a81adac2fa9f7dbf6e9b9.conc) in Concordance::Concordance [Permission denied]

[2018-05-04 17:19:47,608: ERROR/ForkPoolWorker-6] Background calculation error: FileAccessError (/var/lib/corpora/cache/korpus/cc06d16299704ad766d87ef824b5cfd3.conc) in Concordance::Concordance [Permission denied]
[2018-05-04 17:19:47,608: ERROR/ForkPoolWorker-6] Traceback (most recent call last):
  File "/home/administrator/kontext/lib/concworker/__init__.py", line 155, in __call__
    conc.save(initial_args['cachefile'], False, True, False)  # partial
  File "/usr/lib/python2.7/dist-packages/manatee.py", line 980, in save
    return _manatee.Concordance_save(self, *args)
RuntimeError: FileAccessError (/var/lib/corpora/cache/korpus/cc06d16299704ad766d87ef824b5cfd3.conc) in Concordance::Concordance [Permission denied]```

```2018-05-04 17:25:09,653 [plugins.default_conc_persistence] WARNING: Using DB plug-in as archiving storage for concordances. In case you use redis_db then please consider setting archive_dir for default_conc_persistence to prevent filling up RAM with archived concordances.```

I tried chown'ing to root and to www-admin, with no success.

**Comment by tomachalek** [comment]
The problem may come from the fact that _Celery_ and _Gunicorn_ run under different users (_celery_ and _www-data_ respectively). The fact itself is OK but it is necessary to set proper permissions for directories where both _Celery_ and _Gunicorn_ write data.

1. Make sure that Celery runs under the group _www-data_ (check your systemd config file for Celery - look for the _[Service]_ section and _Group_ item).
1. Set proper ownership for your _cache_ directory: `chown www-data:www-data /path/to/your/cache/dir`
1. Set proper permissions for your _cache_ directory (configured in config.xml as part of the _conc_cache_ plug-in):
`chmod g+ws /path/to/your/cache/dir`
1. Remove all the files/dirs in your cache dir

The same applies for the subcorp directory (configured in config.xml in _corpora/users_subcpath_). If you don't want to remove existing subcorpora, just set proper write permissions to make them deletable by users: `find /path/to/your/subcorp/root/dir -type d -exec chmod 664 {} \;`

**Comment by PeterGilles** [comment]
Hm. I tried everything, but the permission problem remains. Application log:
```2018-05-10 11:46:44,752 [actions.concordance] ERROR: FileAccessError (/var/lib/corpora/cache/korpus/db76d518ccfb1396857fe559cd7dc6e9.conc) in Concordance::Concordance [Permission denied]```

There are no errors in the Celery log, which I find strange. When starting celery, there seems to be an error for `plugins.default_query_storage`.

```May 10 11:53:28 Engelmann2 systemd[1]: Starting Celery Service...
-- Subject: Unit celeryd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit celeryd.service has begun starting up.
May 10 11:53:30 Engelmann2 sh[16170]: No handlers could be found for logger "plugins.default_query_storage"
May 10 11:53:30 Engelmann2 sh[16170]: celery multi v4.1.0 (latentcall)
May 10 11:53:30 Engelmann2 sh[16170]: > Starting nodes...
May 10 11:53:30 Engelmann2 sh[16170]:         > worker1@Engelmann2: OK
May 10 11:53:30 Engelmann2 systemd[1]: Started Celery Service.
-- Subject: Unit celeryd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit celeryd.service has finished starting up.
-- 
-- The start-up result is done.```
