### ISSUE TITLE
corpus compiled with errors: ERROR: line 432 - command 'mkstats "$CORPUS" $ATTR $STAT

### ISSUE THREAD

**Issue by Ceprey2** [czcorpus/kontext#3006]
I have the next output during corpus compilation:

root@kontext-container:/opt/kontext/corpora/manatee_registry# compilecorp --no-sketches --recompile-corpus ParallKorpUkrChartUN 
Manatee version: open-2.167.8
Reading corpus configuration...
PATH=/var/lib/manatee/data/parall_ukr_chart_un/
VERTICAL=/var/lib/manatee/vert/parall_ukr_chart_un_vertical
WSDEF=
WSHIST=
SUBCDEF=
WSBASE=
WSATTR=
WSTHES=
WSMINHITS=
WSOLDSCORES=
ALIGNDEF=
ALIGNED=
TERMDEF=
TERMBASE=
ATTRLIST=word,lemma,tag,status,lc,lemma_lc
DIACHRONIC=
SUBCBASE=/var/lib/manatee/data/parall_ukr_chart_un/subcorp/
Corpus is compiled
Vertical text will be read from /var/lib/manatee/vert/parall_ukr_chart_un_vertical
Backing-up log directory to /tmp/compilecorp-log-backup-321
Deleting corpus PATH directory...
Restoring log directory...
Compiling corpus...
[20200330-17:41:41] Available memory 7940MB, estimated usage 198MB
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:15: warning: empty line, ignoring
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:73: warning: empty line, ignoring
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:99: warning: empty line, ignoring
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:143: warning: empty line, ignoring
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:156: warning: empty line, ignoring
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:179: warning: empty line, ignoring
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:190: warning: empty line, ignoring
[20200330-17:41:42] /var/lib/manatee/vert/parall_ukr_chart_un_vertical:414: warning: empty line, ignoring
[20200330-17:41:42] Reading input file finished.
[20200330-17:41:42] Closing structure doc ...
[20200330-17:41:42] warning: structure attribute (doc.file) never present
[20200330-17:41:42] warning: structure attribute (doc.wordcount) never present
[20200330-17:41:42] warning: structure attribute (doc.n) never present
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing structure font ...
[20200330-17:41:42] warning: structure attribute (font.type) never present
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing structure g ...
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing structure head ...
[20200330-17:41:42] warning: structure attribute (head.type) never present
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing structure p ...
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing attribute /var/lib/manatee/data/parall_ukr_chart_un/word ...
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/word) make_lex_srt_file
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing attribute /var/lib/manatee/data/parall_ukr_chart_un/lemma ...
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/lemma) make_lex_srt_file
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing attribute /var/lib/manatee/data/parall_ukr_chart_un/tag ...
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/tag) make_lex_srt_file
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Closing attribute /var/lib/manatee/data/parall_ukr_chart_un/status ...
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/status) make_lex_srt_file
[20200330-17:41:42]             ... finished.
[20200330-17:41:42] Processed 414 lines, 406 positions.
[20200330-17:41:42] Creating dynamic attribute lc
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/lc) make_lex_srt_file
[20200330-17:41:42] Creating regular expression optimization attribute lc
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/lc.regex) make_lex_srt_file
[20200330-17:41:42] Creating dynamic attribute lemma_lc
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/lemma_lc) make_lex_srt_file
[20200330-17:41:42] Creating regular expression optimization attribute lemma_lc
[20200330-17:41:42] lexicon (/var/lib/manatee/data/parall_ukr_chart_un/lemma_lc.regex) make_lex_srt_file
[20200330-17:41:42] Summary of errors encountered in the input file:
[20200330-17:41:42] 8 times: warning type 'empty line'
[20200330-17:41:42] Only first 100 occurrencies emitted, use -v to emit each occurrence.
Compiling frequencies...
100 %
Compiling arf for attribute word
freq already compiled, skipping.
Compiling docf for attribute word
Traceback (most recent call last):
  File "/usr/bin/mkstats", line 107, in <module>
    globals()["compile_" + stat] (corp, attr)
  File "/usr/bin/mkstats", line 85, in compile_docf
    corp.compile_docf (attr, doc.name)
  File "/usr/lib/python3/dist-packages/manatee.py", line 957, in compile_docf
    return _manatee.Corpus_compile_docf(self, attr, docstruc)
RuntimeError: FileAccessError (/var/lib/manatee/data/parall_ukr_chart_un/doc.rng) in BinFile: operator [] [Invalid argument]
<---
ERROR: line 432 - command 'mkstats "$CORPUS" $ATTR $STAT' exited with status: 1
   ... Error at ::main::main called at line 939
--->
Writing log to /var/lib/manatee/data/parall_ukr_chart_un/log/compilecorp_2020-03-30_1741.log
<---
ERROR: line 939 - command 'tee "$TMPLOGFILE"' exited with status: 1
   ... Error at ::main called at line 0
--->

`
Should I correct anything? Does it mean that the corpus has been compiled, though with errors?
Thanks in advance.

**Comment by tomachalek** [comment]
I am afraid I won't be able to help you with this (except for some general stuff like whether the file `/var/lib/manatee/data/parall_ukr_chart_un/doc.rng` actually exists and the access rights are right) as this is purely Manatee engine-related issue. Unfortunately, Manatee error messages are not very helpful in general. Please try [NoSketch Engine Google group](https://groups.google.com/a/sketchengine.co.uk/forum/#!forum/noske).

**Comment by Ceprey2** [comment]
Thanks anyway! I'll certainly try.
