### ISSUE TITLE
AttributeError: 'InitialConc' object has no attribute 'xfreq_dist'

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#3684]
```
2020-12-28 16:25:34,718 [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 975, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 696, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 719, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/kontext/worker/rqworker.py", line 79, in calculate_freqs
    return general.calculate_freqs(args)
  File "/opt/kontext/worker/general.py", line 232, in calculate_freqs
    ans = freq_calc.calc_freqs_bg(args)
  File "/opt/kontext/lib/bgcalc/freq_calc.py", line 245, in calc_freqs_bg
    freqs = [conc.xfreq_dist(cr, args.flimit, args.freq_sort, args.ml, args.ftt_include_empty, args.rel_mode,
  File "/opt/kontext/lib/bgcalc/freq_calc.py", line 245, in <listcomp>
    freqs = [conc.xfreq_dist(cr, args.flimit, args.freq_sort, args.ml, args.ftt_include_empty, args.rel_mode,
AttributeError: 'InitialConc' object has no attribute 'xfreq_dist'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 975, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 696, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 719, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/kontext/worker/rqworker.py", line 79, in calculate_freqs
    return general.calculate_freqs(args)
  File "/opt/kontext/worker/general.py", line 232, in calculate_freqs
    ans = freq_calc.calc_freqs_bg(args)
  File "/opt/kontext/lib/bgcalc/freq_calc.py", line 245, in calc_freqs_bg
    freqs = [conc.xfreq_dist(cr, args.flimit, args.freq_sort, args.ml, args.ftt_include_empty, args.rel_mode,
  File "/opt/kontext/lib/bgcalc/freq_calc.py", line 245, in <listcomp>
    freqs = [conc.xfreq_dist(cr, args.flimit, args.freq_sort, args.ml, args.ftt_include_empty, args.rel_mode,
AttributeError: 'InitialConc' object has no attribute 'xfreq_dist'
```

**Comment by tomachalek** [comment]
We've been able to resolve this by fixing several related issues. This shows up no more in the log.
