### ISSUE TITLE
Unknown action on concordance: p

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#3861]
```
Traceback (most recent call last):
  File "/opt/kontext/public/../lib/controller/__init__.py", line 710, in run
    tmpl, result = self.process_action(methodname, req_args)
  File "/opt/kontext/public/../lib/controller/__init__.py", line 786, in process_action
    method_ans = method(self._request)
  File "/opt/kontext/public/../lib/actions/concordance.py", line 204, in view
    conc = get_conc(corp=self.corp, user_id=self.session_get('user', 'id'), q=self.args.q,
  File "/opt/kontext/public/../lib/conclib/search.py", line 181, in get_conc
    conc = _get_sync_conc(worker=worker, corp=corp, q=q, save=save, subchash=subchash,
  File "/opt/kontext/public/../lib/conclib/search.py", line 96, in _get_sync_conc
    conc = worker.compute_conc(corp, q, samplesize)
  File "/opt/kontext/public/../lib/conclib/calc/base.py", line 110, in compute_conc
    ans_conc = PyConc(corp, q[0][0], q[0][1:], samplesize)
  File "/opt/kontext/public/../lib/conclib/pyconc.py", line 97, in __init__
    raise RuntimeError(translate('Unknown concordance action: %s') % action)
RuntimeError: Neznámá akce na konkordanci: p
```

**Comment by tomachalek** [comment]
Fixed. The error is in general OK as the links triggering it (produced by a web bot) were incorrect. But I've changed the error from 500 to 400 as it is more appropriate.
