### ISSUE TITLE
FileAccessError Concordance::Concordance [Permission denied] in some cases

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#3866]
```
Traceback (most recent call last):
  File "/opt/kontext/public/../lib/controller/__init__.py", line 710, in run
    tmpl, result = self.process_action(methodname, req_args)
  File "/opt/kontext/public/../lib/controller/__init__.py", line 786, in process_action
    method_ans = method(self._request)
  File "/opt/kontext/public/../lib/actions/concordance.py", line 733, in filter
    return self.view(request)
  File "/opt/kontext/public/../lib/actions/concordance.py", line 205, in view
    conc = get_conc(corp=self.corp, user_id=self.session_get('user', 'id'), q=self.args.q,
  File "/opt/kontext/public/../lib/conclib/search.py", line 181, in get_conc
    conc = _get_sync_conc(worker=worker, corp=corp, q=q, save=save, subchash=subchash,
  File "/opt/kontext/public/../lib/conclib/search.py", line 103, in _get_sync_conc
    conc.save(status.cachefile)
  File "/usr/local/lib/python3.8/dist-packages/manatee.py", line 872, in save
    return _manatee.Concordance_save(self, *args)
RuntimeError: FileAccessError (/var/opt/kontext/cache/syn_v8/b5704fc1d7bffd79944fdd7ac68f8384.conc) in Concordance::Concordance [Permission denied]
```

**Comment by tomachalek** [comment]
Fixed in 375457bcb6
