### ISSUE TITLE
Do not log the "unexpected character" error as a "system error" with full stack trace

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#3972]

**Comment by tomachalek** [comment]
```
Traceback (most recent call last):
  File "/opt/kontext/public/../lib/controller/__init__.py", line 714, in run
    tmpl, result = self.process_action(methodname, req_args)
  File "/opt/kontext/public/../lib/controller/__init__.py", line 790, in process_action
    method_ans = method(self._request)
  File "/opt/kontext/public/../lib/actions/concordance.py", line 664, in query_submit
    raise ex
  File "/opt/kontext/public/../lib/actions/concordance.py", line 646, in query_submit
    conc = get_conc(corp=self.corp, user_id=self.session_get('user', 'id'), q=self.args.q,
  File "/opt/kontext/public/../lib/conclib/search.py", line 177, in get_conc
    conc = _get_async_conc(corp=corp, user_id=user_id, q=q, subchash=subchash,
  File "/opt/kontext/public/../lib/conclib/search.py", line 55, in _get_async_conc
    conc_avail = wait_for_conc(cache_map=cache_map, subchash=subchash, q=q, minsize=minsize)
  File "/opt/kontext/public/../lib/conclib/calc/__init__.py", line 99, in wait_for_conc
    has_min_result, finished = _check_result(cache_map, q, subchash, minsize)
  File "/opt/kontext/public/../lib/conclib/calc/__init__.py", line 136, in _check_result
    raise err
plugins.abstract.conc_cache.CalcStatusException: unexpected character \ at position 22
```
