### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#4503]
```
Traceback (most recent call last):
  File "/opt/kontext/public/../lib/controller/__init__.py", line 706, in run
    tmpl, result = self.process_action(methodname, req_args)
  File "/opt/kontext/public/../lib/controller/__init__.py", line 782, in process_action
    method_ans = method(self._request)
  File "/opt/kontext/public/../lib/actions/concordance.py", line 651, in query_submit
    self._set_first_query([q['corpname'] for q in request.json['queries']], qinfo)
  File "/opt/kontext/public/../lib/actions/concordance.py", line 618, in _set_first_query
    data.fc_lemword.split(),
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by tomachalek** [comment]
unable to reproduce
