### ISSUE TITLE
Cannot continue with subc. draft derived from an existing subcoprus

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#5438]
```
Traceback (most recent call last):
File "/opt/kontext/public/../lib/action/control.py", line 211, in wrapper
await amodel.pre_dispatch(None)
File "/opt/kontext/public/../lib/action/model/corpus.py", line 309, in pre_dispatch
raise self.corp.get_error()
File "/opt/kontext/public/../lib/action/model/corpus.py", line 383, in _load_corpus
corp = await self.cf.get_corpus(
File "/opt/kontext/public/../lib/corplib/__init__.py", line 126, in get_corpus
subc = await KSubcorpus.load(corp, corp_ident, self.subcpath)
File "/opt/kontext/public/../lib/corplib/subcorpus/__init__.py", line 140, in load
raise CorpusInstantiationError(f'Subcorpus data not found for "{data_record.id}"')
corplib.errors.CorpusInstantiationError: Subcorpus data not found for "5C8cQ6WK"
```

**Comment by tomachalek** [comment]
It seems this issue is no more relevant.
