### ISSUE TITLE
Missing ability to precalculate *.token for a subcorpus

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#5592]
How to replicate: search a conc and then select "Freq" - "text types"

```
Traceback (most recent call last):
File "/opt/kontext/public/../lib/action/control.py", line 214, in wrapper
ans = await func(amodel, req, resp)
File "/opt/kontext/public/../lib/views/freqs.py", line 85, in freqs
ans = await _freqs(
File "/opt/kontext/public/../lib/views/freqs.py", line 214, in _freqs
calc_result = await calculate_freqs(args)
File "/opt/kontext/public/../lib/bgcalc/freqs/__init__.py", line 208, in calculate_freqs
raise tmp_result
RuntimeError: FileAccessError (/var/local/corpora/subcorp/dc/dcQeYYcm/data.doc.txtype_group.token) in MapBinFile:open [No such file or directory]
```

**Comment by tomachalek** [comment]
Also see NoSkE's 
```py
for cr in fcrit:
            attr = cr.split()[0].split('/')[0]
            if not '.' in attr:
                continue
            missing_norms = not corplib.are_subcorp_stats_compiled(corp, attr,
                                                                   'token:l')
            if missing_norms:
                subcpath = getattr(self._corp(), 'spath', '')
                return corplib.compute_norms(self._corp(), self._user,
                                  attr.split('.')[0], subcpath, self.get_url())
```
