### ISSUE TITLE
Error in processing history

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/kontext#5762]
```
Traceback (most recent call last):
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/control.py", line 217, in wrapper
dub 03 19:15:26 kontext-017 env[200718]:     await amodel.pre_dispatch(None)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/model/corpus.py", line 278, in pre_dispatch
dub 03 19:15:26 kontext-017 env[200718]:     corpname, self._corpus_variant = await self._check_corpus_access(req_args, self._action_props)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/model/corpus.py", line 245, in _check_corpus_access
dub 03 19:15:26 kontext-017 env[200718]:     corpname, redirect = await self._determine_curr_corpus(req_args, is_api)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/model/corpus.py", line 395, in _determine_curr_corpus
dub 03 19:15:26 kontext-017 env[200718]:     queries = await qh.get_user_queries(self.session_get('user', 'id'), self.cf, limit=1)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/plugins/mysql_query_history/__init__.py", line 250, in get_user_queries
dub 03 19:15:26 kontext-017 env[200718]:     tmp = await self._merge_conc_data(item, qdata)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/plugins/mysql_query_history/__init__.py", line 169, in _merge_conc_data
dub 03 19:15:26 kontext-017 env[200718]:     include_empty=get_ac_val(form_data, 'curr_include_empty_values', aitem)))
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/plugins/mysql_query_history/__init__.py", line 140, in get_ac_val
dub 03 19:15:26 kontext-017 env[200718]:     def get_ac_val(data, name, corp): return data[name][corp] if name in data else None
dub 03 19:15:26 kontext-017 env[200718]: KeyError: 'intercorp_v15_en'


During handling of the above exception, another exception occurred:
dub 03 19:15:26 kontext-017 env[200718]: Traceback (most recent call last):
dub 03 19:15:26 kontext-017 env[200718]:   File "handle_request", line 96, in handle_request
dub 03 19:15:26 kontext-017 env[200718]:     if TYPE_CHECKING:
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/control.py", line 238, in wrapper
dub 03 19:15:26 kontext-017 env[200718]:     await resolve_error(amodel, req, resp, ex)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/control.py", line 110, in resolve_error
dub 03 19:15:26 kontext-017 env[200718]:     await amodel.resolve_error_state(req, resp, ans, err)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/model/corpus.py", line 357, in resolve_error_state
dub 03 19:15:26 kontext-017 env[200718]:     await super().resolve_error_state(req, resp, result, err)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/action/model/user.py", line 497, in resolve_error_state
dub 03 19:15:26 kontext-017 env[200718]:     queries = await qh.get_user_queries(self.session_get('user', 'id'), self.cf, limit=1)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/plugins/mysql_query_history/__init__.py", line 250, in get_user_queries
dub 03 19:15:26 kontext-017 env[200718]:     tmp = await self._merge_conc_data(item, qdata)
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/plugins/mysql_query_history/__init__.py", line 169, in _merge_conc_data
dub 03 19:15:26 kontext-017 env[200718]:     include_empty=get_ac_val(form_data, 'curr_include_empty_values', aitem)))
dub 03 19:15:26 kontext-017 env[200718]:   File "/opt/kontext/public/../lib/plugins/mysql_query_history/__init__.py", line 140, in get_ac_val
dub 03 19:15:26 kontext-017 env[200718]:     def get_ac_val(data, name, corp): return data[name][corp] if name in data else None
dub 03 19:15:26 kontext-017 env[200718]: KeyError: 'intercorp_v15_en'

```

**Comment by tomachalek** [comment]
Fixed in rev 9aa90635685275adc
