### ISSUE TITLE
subprocess.CalledProcessError when installing

### ISSUE THREAD

**Issue by archomt** [czcorpus/kontext#5971]
Hello, when I following the [doc/INSTALL.md](https://github.com/czcorpus/kontext/blob/master/doc/INSTALL.md) file to install kontext (root@kontext-container:/opt/kontext# **python3 /opt/kontext/scripts/install/install.py**), The outputs are as follows:

```
Installing requirements...
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

## Installing the NodeSource Node.js 16.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                           
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                                        
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                   
Hit:4 https://dl.yarnpkg.com/debian stable InRelease                                                                              
Hit:5 https://deb.nodesource.com/node_16.x focal InRelease                                                  
Fetched 114 kB in 3s (44.2 kB/s)                         
Reading package lists... Done

## Confirming "focal" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_16.x/dists/focal/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 16.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x focal main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x focal main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                        
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                
Hit:3 https://dl.yarnpkg.com/debian stable InRelease                                                                  
Hit:4 https://deb.nodesource.com/node_16.x focal InRelease          
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Fetched 114 kB in 2s (46.9 kB/s)   
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 16.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (16.20.1-deb-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
useradd: user 'bg-calc' already exists
Setting up nginx...
Installing Manatee-Open...
--2023-07-18 04:59:19--  https://corpora.fi.muni.cz/noske/current/src/manatee-open-2.223.6.tar.gz
Resolving corpora.fi.muni.cz (corpora.fi.muni.cz)... 147.251.51.13
Connecting to corpora.fi.muni.cz (corpora.fi.muni.cz)|147.251.51.13|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘manatee-open-2.223.6.tar.gz’ not modified on server. Omitting download.

libtool: warning: remember to run 'libtool --finish '
File = /usr/local/lib/python3.8/dist-packages/manatee.py already exists!
File = /usr/local/lib/python3.8/dist-packages/_manatee.a already exists!
File = /usr/local/lib/python3.8/dist-packages/_manatee.la already exists!
File = /usr/local/lib/python3.8/dist-packages/_manatee.so already exists!
--2023-07-18 04:59:29--  https://corpora.fi.muni.cz/noske/src/example-corpora/susanne-example-source.tar.bz2
Resolving corpora.fi.muni.cz (corpora.fi.muni.cz)... 147.251.51.13
Connecting to corpora.fi.muni.cz (corpora.fi.muni.cz)|147.251.51.13|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘susanne-example-source.tar.bz2’ not modified on server. Omitting download.

[20230718-04:59:31] Available memory 1955MB, estimated usage 198MB
[20230718-04:59:31] Reading input file finished.
[20230718-04:59:31] Closing structure doc ...
[20230718-04:59:31] warning: structure attribute (doc.wordcount) never present
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/doc.file) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/doc.n) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/doc.wordcount) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing structure font ...
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/font.type) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing structure g ...
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing structure head ...
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/head.type) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing structure p ...
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing attribute /var/lib/manatee/data/susanne/word ...
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/word) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] Creating regular expression optimization attribute word
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/word.regex) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing attribute /var/lib/manatee/data/susanne/lemma ...
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/lemma) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] Creating regular expression optimization attribute lemma
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/lemma.regex) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing attribute /var/lib/manatee/data/susanne/tag ...
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/tag) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Closing attribute /var/lib/manatee/data/susanne/status ...
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/status) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31]             ... finished.
[20230718-04:59:31] Processed 176192 lines, 150426 positions.
[20230718-04:59:31] Creating dynamic attribute lc
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/lc) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] Creating regular expression optimization attribute lc
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/lc.regex) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] Creating dynamic attribute lemma_lc
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/lemma_lc) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] Creating regular expression optimization attribute lemma_lc
[20230718-04:59:31] lexicon (/var/lib/manatee/data/susanne/lemma_lc.regex) writing FSA...
[20230718-04:59:31] Writing FSA finished
[20230718-04:59:31] Summary of errors encountered in the input file:
[20230718-04:59:31] 0 times: warning type 'space in attribute value'
[20230718-04:59:31] 0 times: warning type 'structure opened multiple times on same position'
[20230718-04:59:31] 0 times: warning type 'structure nested too many times'
[20230718-04:59:31] 0 times: warning type 'closing non opened structure'
[20230718-04:59:31] 0 times: warning type 'closing structure automatically'
[20230718-04:59:31] 0 times: warning type 'empty attribute name'
[20230718-04:59:31] 0 times: warning type 'missing equal sign'
[20230718-04:59:31] 0 times: warning type 'undefined structure attribute'
[20230718-04:59:31] 0 times: warning type 'empty line'
[20230718-04:59:31] 0 times: warning type 'too many attributes'
[20230718-04:59:31] 0 times: warning type 'overlong attribute value'
Installing kontext...
[xmldom warning]	unclosed xml attribute 
@#[line:117,col:9]
Traceback (most recent call last):
  File "/opt/kontext/scripts/install/install.py", line 101, in <module>
    steps.SetupKontext(
  File "/opt/kontext/scripts/install/steps.py", line 296, in run
    self.cmd(['npm', 'start', 'build:production'], cwd=self.kontext_path)
  File "/opt/kontext/scripts/install/steps.py", line 100, in cmd
    return subprocess.check_call(args, cwd=cwd, stdout=self.stdout, stderr=self.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'start', 'build:production']' returned non-zero exit status 2.
``` 
Can you please help me with it? Thank you.

**Comment by tomachalek** [comment]
We've found two main issues one of which is already fixed. The second one can be easily avoided when using Ubuntu 22.04. So in case you want to create a new container, just use something like

```
sudo lxc-create -t download -n container_name -- -d ubuntu -r jammy -a amd64
```
With such a container installed and updated KonText source codes, everything should work now.

### Running on Ubuntu 20.04

The crux of the matter lies in the Python 3.x version. Recent versions of KonText necessitate Python 3.10. Although it's feasible to set this up on Ubuntu 20.04, it would require some manual adjustments. At the very least, you'll need to install Python 3.10 and instead of executing your application with the command:

```
python3 public/app.py --address 127.0.0.1 --port 8080
```

you should use:

```
python3.10 public/app.py --address 127.0.0.1 --port 8080
```
