### ISSUE TITLE
Start KonText in a container errors out

### ISSUE THREAD

**Issue by archomt** [czcorpus/kontext#6194]
Hello,

When I try to start konText by entering the command "python3 public/app.py --address 127.0.0.1 --port 8080", I got following errors:

```
root@kontext-container:/opt/kontext# sudo -u www-data python3 public/app.py --address 127.0.0.1 --port 8080
Traceback (most recent call last):
  File "/opt/kontext/public/app.py", line 160, in <module>
    setup_plugins()
  File "/opt/kontext/public/../lib/action/plugin/initializer.py", line 86, in setup_plugins
    init_plugin(plugin.name, optional=plugin.is_optional, module=plugin.forced_module)
  File "/opt/kontext/public/../lib/action/plugin/initializer.py", line 72, in init_plugin
    raise e
  File "/opt/kontext/public/../lib/action/plugin/initializer.py", line 55, in init_plugin
    plg = plugins.install_plugin(name, plugin_module, settings)
  File "/opt/kontext/public/../lib/plugins/__init__.py", line 221, in install_plugin
    _plugins[name] = module.create_instance(*(config,))
  File "/opt/kontext/public/../lib/plugins/__init__.py", line 258, in __call__
    return self._fn(*(conf,) + tuple(v.instance for v in self._args))
  File "/opt/kontext/public/../lib/plugins/default_query_persistence/__init__.py", line 320, in create_instance
    return DefaultQueryPersistence(db=db, auth=auth,
TypeError: DefaultQueryPersistence.__init__() missing 1 required positional argument: 'settings'
```
I followed the instructions in [https://github.com/czcorpus/kontext/blob/master/doc/INSTALL.md](url). 

Thank you.

**Comment by tomachalek** [comment]
Thank you for reporting the issue. By now, it should be OK in the `master` branch. If you can, please confirm whether it works for you.

**Comment by archomt** [comment]
It is working perfectly now. Thank you very much.
