### ISSUE TITLE
Installation: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by PeterGilles** [czcorpus/kontext#6351]
I am trying to install in the kontext-container, however the install script quits with this error:

```
Setting up nginx...
Installing Manatee-Open...
--2024-11-11 15:36:28--  https://corpora.fi.muni.cz/noske/current/src/manatee-open-2.225.8.tar.gz
Resolving corpora.fi.muni.cz (corpora.fi.muni.cz)... 147.251.51.13
Connecting to corpora.fi.muni.cz (corpora.fi.muni.cz)|147.251.51.13|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘manatee-open-2.225.8.tar.gz’ not modified on server. Omitting download.

Traceback (most recent call last):
  File "/opt/kontext/scripts/install/install.py", line 101, in <module>
    steps.SetupManatee(KONTEXT_PATH, stdout, stderr, args.no_cert_check).run(
  File "/opt/kontext/scripts/install/steps.py", line 200, in run
    for patch_path in patch_paths:
TypeError: 'NoneType' object is not iterable
root@kontext-container:/#
```

**Comment by tomachalek** [comment]
Thank you for reporting the problem. The https://github.com/czcorpus/kontext/pull/6377 should fix that.

**Comment by PeterGilles** [comment]
Thanks, it works and I am one step further.

**Comment by PeterGilles** [comment]
I managed to start kontext:

```
root@kontext-container:/opt/kontext# ./venv/bin/python3 public/app.py --address 0.0.0.0 --port 8080 --debugmode
Main  17:45:18 INFO:
  ┌──────────────────────────────────────────────────────────────────────────────────┐
  │                                  Sanic v25.3.0                                   │
  │                         Goin' Fast @ http://0.0.0.0:8080                         │
  ├───────────────────────┬──────────────────────────────────────────────────────────┤
  │                       │      app: kontext                                        │
  │     ▄███ █████ ██     │     mode: debug, w/ 2 workers                            │
  │    ██                 │   server: sanic, HTTP/1.1                                │
  │     ▀███████ ███▄     │   python: 3.12.3                                         │
  │                 ██    │ platform: Linux-5.15.0-112-generic-x86_64-with-glibc2.39 │
  │    ████ ████████▀     │ packages: sanic-routing==23.12.0                         │
  │                       │                                                          │
  │ Build Fast. Run Fast. │                                                          │
  └───────────────────────┴──────────────────────────────────────────────────────────┘

Main  17:45:19 DEBUG:  Creating multiprocessing context using 'spawn'
Main  17:45:19 DEBUG:  Starting a process: Sanic-Server-0-0
Main  17:45:19 DEBUG:  Starting a process: Sanic-Server-1-0
Main  17:45:19 DEBUG:  Starting a process: Sanic-Inspector-0
Srv 1 17:45:20 DEBUG:  Process ack: Sanic-Server-1-0 [20188]
Srv 0 17:45:20 DEBUG:  Process ack: Sanic-Server-0-0 [20187]
Srv 1 17:45:20 INFO:   Starting worker [20188]
Srv 0 17:45:20 INFO:   Starting worker [20187]
Inspe 2025-04-27 17:45:20 +0000 INFO:     Starting worker [20189]
/opt/kontext/public/../lib/plugins/default_corparch/__init__.py:600: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './corplist'
  root = xml.find(self.root_xpath)
Srv 0 17:48:17 DEBUG:  Error Page: The client accepts */*;q=0.1, using 'text' from any
Srv 0 17:48:17 DEBUG:  Error Page: The client accepts */*, using 'text' from any
Srv 1 17:48:17 DEBUG:  Error Page: The client accepts */*, using 'text' from any
Srv 0 17:48:17 DEBUG:  Error Page: The client accepts */*;q=0.8, using 'text' from any
Srv 0 17:48:17 DEBUG:  Error Page: The client accepts */*;q=0.8, using 'text' from any
```

But the starting page is not loading correct and has errors:

<img width="1788" alt="Image" src="https://github.com/user-attachments/assets/4d81fb19-ad5d-41db-8e3c-3c735cc17c90" />

Do you have any idea where I could look for errors?
